stages:
    - doc
pages:
    image: python
    stage: doc
    tags:
        - docker, specific
    script:
        - python create_index.py
    artifacts:
        when: always
        paths:
            - public
